// File generated by FlutterFire CLI.
// To regenerate, run: flutterfire configure
// Or fill in the values manually from your Firebase project console:
// https://console.firebase.google.com → Project Settings → Your Apps
//
// IMPORTANT: Replace every YOUR_* placeholder with the real value before
// building. Commit this file once filled in — these are client-side keys.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Android ────────────────────────────────────────────────────────────────
  // From google-services.json:
  //   apiKey            → client[].api_key[].current_key
  //   appId             → client[].client_info.mobilesdk_app_id
  //   messagingSenderId → project_info.project_number
  //   projectId         → project_info.project_id
  //   storageBucket     → project_info.storage_bucket
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  // ─── iOS ─────────────────────────────────────────────────────────────────────
  // From GoogleService-Info.plist:
  //   apiKey            → API_KEY
  //   appId             → GOOGLE_APP_ID
  //   messagingSenderId → GCM_SENDER_ID
  //   projectId         → PROJECT_ID
  //   storageBucket     → STORAGE_BUCKET
  //   iosClientId       → CLIENT_ID
  //   iosBundleId       → BUNDLE_ID
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.skapps.expenseTracker',
  );

  // ─── macOS ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.skapps.expenseTracker',
  );

  // ─── Web ──────────────────────────────────────────────────────────────────────
  // From Firebase console → Project Settings → Web app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
